// Code generated by lister-gen. DO NOT EDIT.

package v1

// GlobalRoleListerExpansion allows custom methods to be added to
// GlobalRoleLister.
type GlobalRoleListerExpansion interface{}

// GlobalRoleBindingListerExpansion allows custom methods to be added to
// GlobalRoleBindingLister.
type GlobalRoleBindingListerExpansion interface{}

// LoginRecordListerExpansion allows custom methods to be added to
// LoginRecordLister.
type LoginRecordListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}
