// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/wongearl/go-restful-template/pkg/api/iam.ai.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GlobalRoleLister helps list GlobalRoles.
// All objects returned here must be treated as read-only.
type GlobalRoleLister interface {
	// List lists all GlobalRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.GlobalRole, err error)
	// Get retrieves the GlobalRole from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.GlobalRole, error)
	GlobalRoleListerExpansion
}

// globalRoleLister implements the GlobalRoleLister interface.
type globalRoleLister struct {
	indexer cache.Indexer
}

// NewGlobalRoleLister returns a new GlobalRoleLister.
func NewGlobalRoleLister(indexer cache.Indexer) GlobalRoleLister {
	return &globalRoleLister{indexer: indexer}
}

// List lists all GlobalRoles in the indexer.
func (s *globalRoleLister) List(selector labels.Selector) (ret []*v1.GlobalRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.GlobalRole))
	})
	return ret, err
}

// Get retrieves the GlobalRole from the index for a given name.
func (s *globalRoleLister) Get(name string) (*v1.GlobalRole, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("globalrole"), name)
	}
	return obj.(*v1.GlobalRole), nil
}
