// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/wongearl/go-restful-template/pkg/api/iam.ai.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GlobalRoleBindingLister helps list GlobalRoleBindings.
// All objects returned here must be treated as read-only.
type GlobalRoleBindingLister interface {
	// List lists all GlobalRoleBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.GlobalRoleBinding, err error)
	// Get retrieves the GlobalRoleBinding from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.GlobalRoleBinding, error)
	GlobalRoleBindingListerExpansion
}

// globalRoleBindingLister implements the GlobalRoleBindingLister interface.
type globalRoleBindingLister struct {
	indexer cache.Indexer
}

// NewGlobalRoleBindingLister returns a new GlobalRoleBindingLister.
func NewGlobalRoleBindingLister(indexer cache.Indexer) GlobalRoleBindingLister {
	return &globalRoleBindingLister{indexer: indexer}
}

// List lists all GlobalRoleBindings in the indexer.
func (s *globalRoleBindingLister) List(selector labels.Selector) (ret []*v1.GlobalRoleBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.GlobalRoleBinding))
	})
	return ret, err
}

// Get retrieves the GlobalRoleBinding from the index for a given name.
func (s *globalRoleBindingLister) Get(name string) (*v1.GlobalRoleBinding, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("globalrolebinding"), name)
	}
	return obj.(*v1.GlobalRoleBinding), nil
}
