// Code generated by client-gen. DO NOT EDIT.

package v1

type GlobalRoleExpansion interface{}

type GlobalRoleBindingExpansion interface{}

type LoginRecordExpansion interface{}

type UserExpansion interface{}
