// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/wongearl/go-restful-template/pkg/api/core.ai.io/v1"
	scheme "github.com/wongearl/go-restful-template/pkg/client/ai/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HealthsGetter has a method to return a HealthInterface.
// A group's client should implement this interface.
type HealthsGetter interface {
	Healths() HealthInterface
}

// HealthInterface has methods to work with Health resources.
type HealthInterface interface {
	Create(ctx context.Context, health *v1.Health, opts metav1.CreateOptions) (*v1.Health, error)
	Update(ctx context.Context, health *v1.Health, opts metav1.UpdateOptions) (*v1.Health, error)
	UpdateStatus(ctx context.Context, health *v1.Health, opts metav1.UpdateOptions) (*v1.Health, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Health, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.HealthList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Health, err error)
	HealthExpansion
}

// healths implements HealthInterface
type healths struct {
	client rest.Interface
}

// newHealths returns a Healths
func newHealths(c *CoreV1Client) *healths {
	return &healths{
		client: c.RESTClient(),
	}
}

// Get takes name of the health, and returns the corresponding health object, and an error if there is any.
func (c *healths) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Health, err error) {
	result = &v1.Health{}
	err = c.client.Get().
		Resource("healths").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Healths that match those selectors.
func (c *healths) List(ctx context.Context, opts metav1.ListOptions) (result *v1.HealthList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.HealthList{}
	err = c.client.Get().
		Resource("healths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested healths.
func (c *healths) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("healths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a health and creates it.  Returns the server's representation of the health, and an error, if there is any.
func (c *healths) Create(ctx context.Context, health *v1.Health, opts metav1.CreateOptions) (result *v1.Health, err error) {
	result = &v1.Health{}
	err = c.client.Post().
		Resource("healths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(health).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a health and updates it. Returns the server's representation of the health, and an error, if there is any.
func (c *healths) Update(ctx context.Context, health *v1.Health, opts metav1.UpdateOptions) (result *v1.Health, err error) {
	result = &v1.Health{}
	err = c.client.Put().
		Resource("healths").
		Name(health.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(health).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *healths) UpdateStatus(ctx context.Context, health *v1.Health, opts metav1.UpdateOptions) (result *v1.Health, err error) {
	result = &v1.Health{}
	err = c.client.Put().
		Resource("healths").
		Name(health.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(health).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the health and deletes it. Returns an error if one occurs.
func (c *healths) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("healths").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *healths) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("healths").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched health.
func (c *healths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Health, err error) {
	result = &v1.Health{}
	err = c.client.Patch(pt).
		Resource("healths").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
