// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/wongearl/go-restful-template/pkg/client/ai/clientset/versioned/typed/iam.ai.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIamV1 struct {
	*testing.Fake
}

func (c *FakeIamV1) GlobalRoles() v1.GlobalRoleInterface {
	return &FakeGlobalRoles{c}
}

func (c *FakeIamV1) GlobalRoleBindings() v1.GlobalRoleBindingInterface {
	return &FakeGlobalRoleBindings{c}
}

func (c *FakeIamV1) LoginRecords() v1.LoginRecordInterface {
	return &FakeLoginRecords{c}
}

func (c *FakeIamV1) Users() v1.UserInterface {
	return &FakeUsers{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIamV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
