// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	coreaiiov1 "github.com/wongearl/go-restful-template/pkg/api/core.ai.io/v1"
	versioned "github.com/wongearl/go-restful-template/pkg/client/ai/clientset/versioned"
	internalinterfaces "github.com/wongearl/go-restful-template/pkg/client/ai/informers/externalversions/internalinterfaces"
	v1 "github.com/wongearl/go-restful-template/pkg/client/ai/listers/core.ai.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HealthInformer provides access to a shared informer and lister for
// Healths.
type HealthInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.HealthLister
}

type healthInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewHealthInformer constructs a new informer for Health type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHealthInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHealthInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredHealthInformer constructs a new informer for Health type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHealthInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1().Healths().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1().Healths().Watch(context.TODO(), options)
			},
		},
		&coreaiiov1.Health{},
		resyncPeriod,
		indexers,
	)
}

func (f *healthInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHealthInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *healthInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&coreaiiov1.Health{}, f.defaultInformer)
}

func (f *healthInformer) Lister() v1.HealthLister {
	return v1.NewHealthLister(f.Informer().GetIndexer())
}
