// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/wongearl/go-restful-template/pkg/client/ai/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Healths returns a HealthInformer.
	Healths() HealthInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Healths returns a HealthInformer.
func (v *version) Healths() HealthInformer {
	return &healthInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
