// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	iamaiiov1 "github.com/wongearl/go-restful-template/pkg/api/iam.ai.io/v1"
	versioned "github.com/wongearl/go-restful-template/pkg/client/ai/clientset/versioned"
	internalinterfaces "github.com/wongearl/go-restful-template/pkg/client/ai/informers/externalversions/internalinterfaces"
	v1 "github.com/wongearl/go-restful-template/pkg/client/ai/listers/iam.ai.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LoginRecordInformer provides access to a shared informer and lister for
// LoginRecords.
type LoginRecordInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.LoginRecordLister
}

type loginRecordInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewLoginRecordInformer constructs a new informer for LoginRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLoginRecordInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLoginRecordInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredLoginRecordInformer constructs a new informer for LoginRecord type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLoginRecordInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IamV1().LoginRecords().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IamV1().LoginRecords().Watch(context.TODO(), options)
			},
		},
		&iamaiiov1.LoginRecord{},
		resyncPeriod,
		indexers,
	)
}

func (f *loginRecordInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLoginRecordInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *loginRecordInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&iamaiiov1.LoginRecord{}, f.defaultInformer)
}

func (f *loginRecordInformer) Lister() v1.LoginRecordLister {
	return v1.NewLoginRecordLister(f.Informer().GetIndexer())
}
