// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1 "github.com/wongearl/go-restful-template/pkg/api/core.ai.io/v1"
	iamaiiov1 "github.com/wongearl/go-restful-template/pkg/api/iam.ai.io/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=core.ai.io, Version=v1
	case v1.SchemeGroupVersion.WithResource("healths"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1().Healths().Informer()}, nil

		// Group=iam.ai.io, Version=v1
	case iamaiiov1.SchemeGroupVersion.WithResource("globalroles"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Iam().V1().GlobalRoles().Informer()}, nil
	case iamaiiov1.SchemeGroupVersion.WithResource("globalrolebindings"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Iam().V1().GlobalRoleBindings().Informer()}, nil
	case iamaiiov1.SchemeGroupVersion.WithResource("loginrecords"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Iam().V1().LoginRecords().Informer()}, nil
	case iamaiiov1.SchemeGroupVersion.WithResource("users"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Iam().V1().Users().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
